packages:
  - apps/*
  - packages/*

catalogs:
  default:
    "@tailwindcss/vite": ^4.1.18
    "@vitest/coverage-v8": ^4.0.18
    electron: 39.2.6
    solid-js: ^1.9.0
    tailwindcss: ^4.1.18
    typescript: ^5.9.3
    vite: ^7.2.6
    vite-plugin-dts: 4.5.4
    vite-plugin-solid: ^2.11.0
    vitest: ^4.0.18

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - electron
  - onnxruntime-node
