packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  default:
    vite: ^7.2.6
    typescript: ^5.9.3
    vite-plugin-dts: 4.5.4
    electron: 39.2.6
    solid-js: ^1.9.0
    "vite-plugin-solid": ^2.11.0
    "@tailwindcss/vite": ^4.1.18
    tailwindcss: ^4.1.18
    "@vitest/coverage-v8": ^4.0.18
    vitest: ^4.0.18

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - electron
  - onnxruntime-node
