CREATE TABLE `observational_memory` (
	`id` text PRIMARY KEY,
	`lookup_key` text NOT NULL,
	`scope` text NOT NULL,
	`resource_id` text,
	`thread_id` text,
	`active_observations` text NOT NULL,
	`active_observations_pending_update` text,
	`buffered_observation_chunks` text,
	`buffered_reflection` text,
	`buffered_reflection_tokens` integer,
	`buffered_reflection_input_tokens` integer,
	`reflected_observation_line_count` integer,
	`observed_message_ids` text,
	`observed_timezone` text,
	`origin_type` text NOT NULL,
	`generation_count` integer NOT NULL,
	`config` text NOT NULL,
	`pending_message_tokens` integer NOT NULL,
	`total_tokens_observed` integer NOT NULL,
	`observation_token_count` integer NOT NULL,
	`is_observing` integer DEFAULT false NOT NULL,
	`is_reflecting` integer DEFAULT false NOT NULL,
	`is_buffering_observation` integer DEFAULT false NOT NULL,
	`is_buffering_reflection` integer DEFAULT false NOT NULL,
	`last_buffered_at_tokens` integer DEFAULT 0 NOT NULL,
	`last_observed_at` integer,
	`last_reflection_at` integer,
	`last_buffered_at_time` integer,
	`metadata` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_observational_memory_resource_id_projects_id_fk` FOREIGN KEY (`resource_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
	CONSTRAINT `fk_observational_memory_thread_id_sessions_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `sessions`(`id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE INDEX `observational_memory_lookup_key_idx` ON `observational_memory` (`lookup_key`);