/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BlockRange {
  /** 1-indexed inclusive last line of the resolved block. */
  endLine: number;
  /** 1-indexed inclusive first line of the resolved block. */
  startLine: number;
}

/**
 * Find the outermost named tree-sitter node that begins on `options.line`.
 * Returns its 1-indexed inclusive line span, or null when the language is
 * unrecognized, the line is blank/out-of-range, no node begins there, or the
 * resolved subtree contains a syntax error.
 */
export declare function blockRangeAt(options: BlockRangeOptions): BlockRange | null;

export interface BlockRangeOptions {
  /** Source code to inspect. */
  code: string;
  /** Language alias (e.g. "rust", "typescript"); overrides path inference. */
  lang?: string;
  /** 1-indexed source line the block must begin on. */
  line: number;
  /** File path used to infer language by extension when `lang` is None. */
  path?: string;
}
